vim.api.nvim_set_keymap('n', '<ESC>', ':nohlsearch<CR><ESC>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'j', 'gj', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'k', 'gk', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<down>', 'gj', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<up>', 'gk', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'ss', '<C-w>s<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'sv', '<C-w>v<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', ',df', ':<C-u>lua vim.diagnostic.open_float()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', ',ds', ':<C-u>lua vim.diagnostic.setqflist()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'jj', '<ESC>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-f>', '<Right>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-f><C-f>', '<ESC><S-a>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', ';', ':', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'tst', ':<C-u>TestSample<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'cp', ':<C-u>Copilot panel<CR>', { noremap = true, silent = true })
